### ISSUE TITLE
Time left

### ISSUE THREAD

**Issue by tonertiffi** [swartjean/ha-eskom-loadshedding#16]
Great integration was very happy to see this, thank you, was wondering if it would be possible to have it based on area the amount off time and time left on the schedule in your area for example :

load sheading will begin in 3hours
when you in load sheading time left in the stage eg: 1h45min

something similar to the eskom app

**Comment by swartjean** [comment]
Hi @tonertiffi, sorry for taking so long to get back to you.

I will leave this issue open in case anybody wants to take a stab at it, but there are some annoying complications that make it a bit tricky.

Eskom has API endpoints for fetching zone IDs by street address and for fetching schedules from those zone IDs. Unfortunately their API only has schedules for Eskom-supplied areas. Most metros (City of Cape Town) have their schedules published on local municipal websites with no APIs.

This changes the problem from a simple API call to a rather involved web scraping task, where every municipality or different schedule format needs to be handled individually. I strongly suspect this is what EskomSePush does with great success. 

First prize would be if the ESP devs exposed their collected zone and schedule information through an API. Otherwise somebody is going to have to effectively replicate their work in this integration.

I will keep an eye on the API and schedules exposed by Eskom and if anything changes to make the task easier I will definitely update this integration.

**Comment by tonertiffi** [comment]
Good morning.

Trust you well thank you for the reply.

It would be great to have it, would defenently be a game changer with regards to solar inverters, homes be able to know how long  it would be till the outage is going to affect you.

Thanks for the effort always appreciated

Will keep an eye on this integration

Kind regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cliffordwhansen** [comment]
I have started looking into doing something like this using the "scraping" method, but yes getting this to be usefull for everyone is going to be tricky.

@swartjean I do see the ESP has a business API, not sure if you have contacted them yet, can I do so on behalf of this project?

**Comment by swartjean** [comment]
Hi @cliffordwhansen - apologies for being AWOL on this project for a while. Work has kept me very busy lately.

I have not yet contacted ESP about their business API. It would be an ideal fit for this project otherwise we are going to need to effectively re-implement all of the web scraping that they are doing. Like you said, it will take a huge amount of work to get it in a state where it will be useful for everybody and it is probably not worth the time and effort for a project of this scale.

I would be more than happy for you to contact ESP on behalf of the project. #19 refers directly to integration with the business API - will you please update that issue with their feedback? I have my concerns that they will not want to share access to their business API as it may undermine their business model, but let's see what they say.

**Comment by swartjean** [comment]
This has been added. Please see #19.
