### ISSUE TITLE
Can't add integration without API key now. 

### ISSUE THREAD

**Issue by NyvenZA** [swartjean/ha-eskom-loadshedding#22]
I am using the HACS option in Home assistant to add the integration and it worked. 
Now you have to enter an ESP API key to be able to add the integration. No option to add without it. Not sure it it would work without it. 

I had this working until I upgraded and wanted to use the ESP facilities. I don't have a API key yet, so I just tried to add the integration back without a key and it now requires an API KEY to continue. 

I tried to enter "0" and it allowed it, but I assume that it would actually use that, which may cause some issues. Not going to apply it.

-->

## Version v1.1.0

![image](https://user-images.githubusercontent.com/64709994/195201097-ad31760e-3cad-49b0-8022-5f59a7743aef.png)

**Comment by swartjean** [comment]
Hi, yes the integration has been updated to use the ESP API instead of the Eskom one which had reliability issues and very limited functionality. Unfortunately all of the ESP functionality is locked behind their API, which means that every user needs a key in order to use the integration. There is no point to being able to add the integration without a key, as there is no real functionality without the key.

You'll need to apply here - https://sepush.co.za/
Scroll to the bottom and see the ["API Access Request"](https://docs.google.com/forms/d/e/1FAIpQLSeZhAkhDaQX_mLT2xn41TkVjLkOH3Py3YWHi_UqQP4niOY01g/viewform), it's currently a Google doc that you fill out with a brief motivation.

If you want to use the integration without the ESP API you will need to install the previous version.

Will investigate why entering 0 as an API key worked for you, but there should be a validation step that fails at that point.
