### ISSUE TITLE
Calendar event not active

### ISSUE THREAD

**Issue by w1tw0lf** [swartjean/ha-eskom-loadshedding#24]
Comparing to other calendar integrations, it doesn´t change from off to on when start time is reached. 

![image](https://user-images.githubusercontent.com/55384762/195365869-6b4a5493-7f75-4fa3-be50-d75c719eef9e.png)

**Comment by swartjean** [comment]
Hi, this is expected behavior at the moment. How frequently the "value" (the next or current event) that calendar entity displays is updated depends on the scan interval. Since the integration defaults to a two hour scan interval, the entity state will only update every two hours.

As far as I can see this is the case with pretty much all calendar integrations. Some will scan more frequently than others, which will lead to the event state updating more quickly when the event start time is reached. Obviously if ESP issued API keys with larger usage quotas we could make the default scan interval shorter. 

All that being said, I don't really see an issue here. See the [calendar integration docs](https://www.home-assistant.io/integrations/calendar/):

> A calendar entity has state and attributes represent the next upcoming event (only). A calendar trigger is much more flexible, has fewer limitations, and is recommended for automations, instead of using the entity state.

Calendar triggers should be used for automations, not the entity state. As long as the calendar entity fetches upcoming events before they begin you can create automations that trigger exactly at the start time of the event (or +/- a time offset), regardless of the scan interval.

If what you are after is a real-time loadshedding status sensor that you can put on a card I would recommend creating an new `input_boolean` and a template `binary_sensor` to read its state (you can leave this out if you don't mind displaying an `input_boolean` as a "sensor" on your dashboard). Then create a calendar automation that turns on the `input_boolean` when the loadshedding event starts, and turns it off when the event ends. 

Without something like this I think that you will always be at the mercy of the device scan interval.

**Comment by w1tw0lf** [comment]
I don´t think it has anything to do with the scan interval. As the scan interval will only update/add/remove events in the calendar.

I use google calendar integration extensively. The calendar status changes based on an active event, in other words, it would turn on at the start time and turn off at the end time.

Here is a screenshot from home assistant forums as and example:

![image](https://user-images.githubusercontent.com/55384762/195413273-8f7794e8-5a15-4d29-a7f2-c6c23bdc6e79.png)

**Comment by w1tw0lf** [comment]
Just created a test event on google calendar and here is the results as reference 

![Screenshot_2022-10-12-20-35-23_3840x1080](https://user-images.githubusercontent.com/55384762/195422060-1acadbfa-5371-4d5d-89e1-a1b69485efa2.png)

**Comment by swartjean** [comment]
Thanks for this, I'll take a look at the Google calendar integration source and see what they are doing.

**Comment by swartjean** [comment]
I took a look at the Google calendar integration and I've pushed an updated to replicate its behaviour. They use a combination of coordinator callbacks and polling to query the API and update the calendar state at different rates. I learned something new, so thanks for pointing it out!

The entities should now update as follows:

* API updates - 2 hours (default)
* Updates to upcoming calendar events - 15 mins
* Updates to calendar entity state - 30 seconds

So you should now see the calendar entity state update within 30 seconds of the loadshedding event starting. 👍 
I haven't investigated how to make this update rate configurable, but I'm sure it should be possible. Will check it out down the line if there is demand.

**Comment by w1tw0lf** [comment]
Pleasure and thank you 🙂
