### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by brafster** [swartjean/ha-eskom-loadshedding#4]
Hi,

I've been using my own sensor for the last year. Command line sensor that polls the status. How is this different? One issue I do have is that the eskom status isn't stable. So even if it's stage 2 for the whole day, it will switch between 2 and 0 quite a few times. Not sure if you've managed to sort that out...

**Comment by swartjean** [comment]
Hi @brafster,

The simple answer is that right now there is not much difference in terms of functionality between using a command line sensor and using this integration, but there may be differences in stability.

That being said, I do plan to continue adding features to this integration, such as zone and schedule lookups based on the location configured in your HA instance.

With regards to stability, I have seen the same issues that you have mentioned. The Eskom API occasionally returns a value of `0` when it is queried, even though this isn't a valid state (since no loadshedding is represented as a `1`). I have also seem issues where the server just drops client connections in the middle of a request.

To combat this, I have made this integration quite aggressive in how it retries failed requests, both in terms of networking errors, and in terms of sanity checks (like the `0` response you mentioned). Since I have been using this on my own system I have not seen the sensor fail to get a response (i.e. become unavailable), or return an invalid loadshedding status.  

Hope that helps 👍

**Comment by brafster** [comment]
Thanks for the feedback. And thanks for this awesome piece of work! Will install it and give it a try and let you know.

**Comment by swartjean** [comment]
@brafster no problem at all, hope it works well 👍 

I'm going to close this issue, but feel free to open another or reopen it if you have any other questions/comments!
