### ISSUE TITLE
[Info] Pulling Loadshedding Scheduels from an API.

### ISSUE THREAD

**Issue by ToxicDeathX** [swartjean/ha-eskom-loadshedding#6]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Pulling Loadshedding Schedule from API.

**Describe alternatives you've considered**
N/A

**Additional context**
**https://mybroadband.co.za/forum/threads/loadshedding-api.672196/post-24589864** I found this article and had a look at it, Could you please add an section using config flows etc to configure the add-on with the remaining data needed and the just adapt the current eskom interface file to read the data and display as an entity.

**Comment by swartjean** [comment]
Hi @ToxicDeathX,

Thanks for the feedback. Yes, I am planning to make an update along these lines, but I would like for the suburb to be automatically determined using the location in your home assistant configuration.

The only unfortunate caveat here is that the Eskom API only supports schedule lookups for Eskom-supplied areas. Most metros maintain their own schedules, which would require more involved data aggregation. That being said, I will still be implementing this so that it can be leveraged by Eskom-supplied users.

**Comment by ToxicDeathX** [comment]
Makes sense with it only being eskom related areas, Just thought id drop some more information for you incase you didn't have the information btw nice addon.

**Comment by swartjean** [comment]
Thanks for the heads up and feedback 👍
